# Generated by Django 2.1.7 on 2019-03-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=100000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100000, null=True)),
                ('telegram_id', models.CharField(max_length=100000, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='budget.Payer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
