# Generated by Django 2.1.7 on 2019-03-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='message',
            new_name='update',
        ),
    ]
