# Generated by Django 2.1.7 on 2019-03-05 12:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20190305_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyquote',
            name='quote',
            field=jsonfield.fields.JSONField(),
        ),
    ]
