# Generated by Django 2.2 on 2019-04-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20190404_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name_plural': 'Currencies'},
        ),
    ]
